ALTER TABLE IF EXISTS public.empresas
ADD COLUMN IF NOT EXISTS contact_person TEXT,
ADD COLUMN IF NOT EXISTS contact_phone TEXT,
ADD COLUMN IF NOT EXISTS company_logo TEXT,
ADD COLUMN IF NOT EXISTS company_bio TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

ALTER TABLE IF EXISTS public.company_requirements
ADD COLUMN IF NOT EXISTS req_experience_years INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pay_per_mile_min NUMERIC,
ADD COLUMN IF NOT EXISTS pay_per_mile_max NUMERIC,
ADD COLUMN IF NOT EXISTS requires_travel_interview BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS home_time TEXT,
ADD COLUMN IF NOT EXISTS offered_freight_types TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
